module.exports = {
  "env": {
    "es6": true,
    "browser": true,
    "node": true
  },
  "extends": [
    "standard",
    "plugin:import/recommended",
    "plugin:eslint-comments/recommended",
    "plugin:jsonc/recommended-with-jsonc",
    "plugin:yml/standard",
    "eslint-config-airbnb-base"
  ],
  "plugins": [
    "html",
    "unused-imports"
  ],
  "settings": {
    "import/resolver": {
      "node": {
        "extensions": [".js", ".mjs", ".ts", ".d.ts"]
      }
    }
  },
  "globals": {
    "document": "readonly",
    "navigator": "readonly",
    "window": "readonly"
  },
  "parserOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "overrides": [
    {
      "files": ["*.json", "*.json5"],
      "parser": "jsonc-eslint-parser",
      "rules": {
        "quote-props": ["error", "always"],
        "comma-dangle": ["error", "never"]
      }
    },
    {
      "files": ["package.json"],
      "parser": "jsonc-eslint-parser",
      "rules": {
        "jsonc/sort-keys": [
          "error",
          {
            "pathPattern": "^$",
            "order": [
              "name",
              "version",
              "description",
              "keywords",
              "license",
              "repository",
              "funding",
              "author",
              "type",
              "files",
              "exports",
              "main",
              "module",
              "unpkg",
              "bin",
              "scripts",
              "husky",
              "lint-staged",
              "peerDependencies",
              "peerDependenciesMeta",
              "dependencies",
              "devDependencies",
              "eslintConfig"
            ]
          },
          {
            "pathPattern": "^(?:dev|peer|optional|bundled)?[Dd]ependencies$",
            "order": { "type": "asc" }
          }
        ]
      }
    }
  ],
  "rules": {
    "no-debugger": "off",
    "no-console": "off",
    "no-shadow": "off",
    "no-loop-func": "off",
    "no-return-await": "off",
    "template-curly-spacing": "off",
    "camelcase": "off",
    "consistent-return": "off",
    "no-restricted-syntax": "off",
    "indent": ["error", 4, { "SwitchCase": 1, "ignoredNodes": ["TemplateLiteral"] }],
    "max-len": ["error", { "code": 180 }],
    "linebreak-style": "off",
    "arrow-parens": "off",
    "generator-star-spacing": "off",
    "operator-linebreak": ["error", "before"],
    "eol-last": "off",
    "global-require": "off",
    "semi": ["error", "never"],
    "comma-dangle": ["error", "only-multiline"],
    "no-underscore-dangle": "off",
    "space-before-function-paren": ["error", { "named": "never", "anonymous": "never", "asyncArrow": "always" }],
    "keyword-spacing": "off",
    "no-new": "off",
    "default-case": "off",
    "func-names": ["error", "as-needed"],
    "no-unused-expressions": ["error", { "allowShortCircuit": true, "allowTernary": true }],
    "no-param-reassign": ["error", { "props": false }],
    "no-plusplus": ["error", { "allowForLoopAfterthoughts": true }],
    "no-confusing-arrow": ["error", { "allowParens": true }],
    "no-mixed-operators": "off",
    "no-bitwise": "off",
    "import/no-unresolved": "off",
    "import/extensions": "off",
    "import/first": "off",
    "import/no-dynamic-require": "off",
    "import/no-extraneous-dependencies": "off",
    "import/named": "off",
    "import/no-named-as-default": "off",
    "import/no-named-as-default-member": "off",
    "import/no-duplicates": "off",
    "import/no-cycle": "off",
    "import/order": "off",
    "import/no-self-import": "off",
    "import/no-useless-path-segments": "off",
    "import/prefer-default-export": "off",
    "class-methods-use-this": "off",
    "max-classes-per-file": "off",
    "object-curly-newline": "off",
    "implicit-arrow-linebreak": "off",

    "accessor-pairs": ["error", { "enforceForClassMembers": true, "setWithoutGet": true }],
    "array-callback-return": "error",
    "block-scoped-var": "error",
    "constructor-super": "error",
    "default-case-last": "error",
    "dot-notation": ["error", { "allowKeywords": true }],
    "eqeqeq": ["error", "smart"],
    "new-cap": ["error", { "capIsNew": false, "newIsCap": true, "properties": true }],
    "no-alert": "error",
    "no-array-constructor": "error",
    "no-async-promise-executor": "error",
    "no-caller": "error",
    "no-case-declarations": "error",
    "no-class-assign": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": ["error", "always"],
    "no-const-assign": "error",
    "no-control-regex": "error",
    "no-delete-var": "error",
    "no-dupe-args": "error",
    "no-dupe-class-members": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty": ["error", { "allowEmptyCatch": true }],
    "no-empty-character-class": "error",
    "no-empty-pattern": "error",
    "no-eval": "error",
    "no-ex-assign": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-extra-boolean-cast": "error",
    "no-fallthrough": "error",
    "no-func-assign": "error",
    "no-global-assign": "error",
    "no-implied-eval": "error",
    "no-import-assign": "error",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "error",
    "no-iterator": "error",
    "no-labels": ["error", { "allowLoop": false, "allowSwitch": false }],
    "no-lone-blocks": "error",
    "no-loss-of-precision": "error",
    "no-misleading-character-class": "error",
    "no-multi-str": "error",
    "no-new-func": "error",
    "no-new-native-nonconstructor": "error",
    "no-new-wrappers": "error",
    "no-obj-calls": "error",
    "no-octal": "error",
    "no-octal-escape": "error",
    "no-proto": "error",
    "no-prototype-builtins": "error",
    "no-redeclare": ["error", { "builtinGlobals": false }],
    "no-regex-spaces": "error",
    "no-restricted-globals": [
      "error",
      { "message": "Use `globalThis` instead.", "name": "global" },
      { "message": "Use `globalThis` instead.", "name": "self" }
    ],
    "no-restricted-properties": [
      "error",
      { "message": "Use Object.getPrototypeOf or Object.setPrototypeOf instead.", "property": "__proto__" },
      { "message": "Use Object.defineProperty instead.", "property": "__defineGetter__" },
      { "message": "Use Object.defineProperty instead.", "property": "__defineSetter__" },
      { "message": "Use Object.getOwnPropertyDescriptor instead.", "property": "__lookupGetter__" },
      { "message": "Use Object.getOwnPropertyDescriptor instead.", "property": "__lookupSetter__" }
    ],
    "no-self-assign": ["error", { "props": true }],
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-shadow-restricted-names": "error",
    "no-sparse-arrays": "error",
    "no-template-curly-in-string": "error",
    "no-this-before-super": "error",
    "no-throw-literal": "error",
    "no-undef": "error",
    "no-undef-init": "error",
    "no-unexpected-multiline": "error",
    "no-unmodified-loop-condition": "error",
    "no-unneeded-ternary": ["error", { "defaultAssignment": false }],
    "no-unreachable": "error",
    "no-unreachable-loop": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unused-vars": ["error", { "args": "none", "caughtErrors": "none", "ignoreRestSiblings": true, "vars": "all" }],
    "no-use-before-define": ["error", { "classes": false, "functions": false, "variables": true }],
    "no-useless-backreference": "error",
    "no-useless-call": "error",
    "no-useless-catch": "error",
    "no-useless-computed-key": "error",
    "no-useless-constructor": "error",
    "no-useless-rename": "error",
    "no-useless-return": "error",
    "no-var": "error",
    "no-with": "error",
    "object-shorthand": ["error", "always", { "avoidQuotes": true, "ignoreConstructors": false }],
    "one-var": ["error", { "initialized": "never" }],
    "prefer-arrow-callback": ["error", { "allowNamedFunctions": false, "allowUnboundThis": true }],
    "prefer-const": ["error", { "destructuring": "all", "ignoreReadBeforeAssign": true }],
    "prefer-exponentiation-operator": "error",
    "prefer-promise-reject-errors": "error",
    "prefer-regex-literals": ["error", { "disallowRedundantWrapping": true }],
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    "symbol-description": "error",
    "unicode-bom": ["error", "never"],
    "unused-imports/no-unused-imports": "error",
    "unused-imports/no-unused-vars": [
      "error",
      {
        "args": "after-used",
        "argsIgnorePattern": "^_",
        "ignoreRestSiblings": true,
        "vars": "all",
        "varsIgnorePattern": "^_"
      }
    ],
    "use-isnan": ["error", { "enforceForIndexOf": true, "enforceForSwitchCase": true }],
    "valid-typeof": ["error", { "requireStringLiterals": true }],
    "vars-on-top": "error",
    "yoda": ["error", "never"]
  }
}
