import type { OptionsIsInEditor, OptionsOverrides, TypedFlatConfigItem } from '../types'

import globals from 'globals'

import { pluginAntfu, pluginUnusedImports } from '../plugins'

export async function javascript(
    options: OptionsIsInEditor & OptionsOverrides = {},
): Promise<TypedFlatConfigItem[]> {
    const {
        isInEditor = false,
        overrides = {},
    } = options

    return [
        {
            languageOptions: {
                ecmaVersion: 'latest',
                globals: {
                    ...globals.browser,
                    ...globals.es2021,
                    ...globals.node,
                    document: 'readonly',
                    navigator: 'readonly',
                    window: 'readonly',
                },
                parserOptions: {
                    ecmaFeatures: {
                        jsx: true,
                    },
                    ecmaVersion: 'latest',
                    sourceType: 'module',
                },
                sourceType: 'module',
            },
            linterOptions: {
                reportUnusedDisableDirectives: true,
            },
            name: 'antfu/javascript/setup',
        },
        {
            name: 'antfu/javascript/rules',
            plugins: {
                'antfu': pluginAntfu,
                'unused-imports': pluginUnusedImports,
            },
            rules: {
                'accessor-pairs': ['error', { enforceForClassMembers: true, setWithoutGet: true }],

                'antfu/no-top-level-await': 'error',

                'array-callback-return': 'error',
                'arrow-parens': 'off',
                'block-scoped-var': 'error',
                'camelcase': 'off',
                'class-methods-use-this': 'off',
                'comma-dangle': ['error', 'only-multiline'],
                'consistent-return': 'off',
                'constructor-super': 'error',
                'default-case': 'off',
                'default-case-last': 'error',
                'dot-notation': ['error', { allowKeywords: true }],
                'eol-last': 'off',
                'eqeqeq': ['error', 'smart'],
                'func-names': ['error', 'as-needed'],
                'generator-star-spacing': 'off',
                'global-require': 'off',
                'implicit-arrow-linebreak': 'off',
                'import/first': 'off',
                'import/no-duplicates': 'off',
                'import/prefer-default-export': 'off',
                'keyword-spacing': 'off',
                'linebreak-style': 'off',
                'max-classes-per-file': 'off',
                'max-len': ['error', { code: 180 }],
                'new-cap': ['error', { capIsNew: false, newIsCap: true, properties: true }],
                'no-alert': 'error',
                'no-array-constructor': 'error',
                'no-async-promise-executor': 'error',
                'no-bitwise': 'off',
                'no-caller': 'error',
                'no-case-declarations': 'error',
                'no-class-assign': 'error',
                'no-compare-neg-zero': 'error',
                'no-cond-assign': ['error', 'always'],
                'no-confusing-arrow': ['error', { allowParens: true }],
                'no-console': 'off',
                'no-const-assign': 'error',
                'no-control-regex': 'error',
                'no-debugger': 'off',
                'no-delete-var': 'error',
                'no-dupe-args': 'error',
                'no-dupe-class-members': 'error',
                'no-dupe-keys': 'error',
                'no-duplicate-case': 'error',
                'no-empty': ['error', { allowEmptyCatch: true }],
                'no-empty-character-class': 'error',
                'no-empty-pattern': 'error',
                'no-eval': 'error',
                'no-ex-assign': 'error',
                'no-extend-native': 'error',
                'no-extra-bind': 'error',
                'no-extra-boolean-cast': 'error',
                'no-fallthrough': 'error',
                'no-func-assign': 'error',
                'no-global-assign': 'error',
                'no-implied-eval': 'error',
                'no-import-assign': 'error',
                'no-invalid-regexp': 'error',
                'no-irregular-whitespace': 'error',
                'no-iterator': 'error',
                'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
                'no-lone-blocks': 'error',
                'no-loop-func': 'off',
                'no-loss-of-precision': 'error',
                'no-misleading-character-class': 'error',
                'no-mixed-operators': 'off',
                'no-multi-str': 'error',
                'no-new': 'off',
                'no-new-func': 'error',
                'no-new-native-nonconstructor': 'error',
                'no-new-wrappers': 'error',
                'no-obj-calls': 'error',
                'no-octal': 'error',
                'no-octal-escape': 'error',
                'no-param-reassign': ['error', { props: false }],
                'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
                'no-proto': 'error',
                'no-prototype-builtins': 'error',
                'no-redeclare': ['error', { builtinGlobals: false }],
                'no-regex-spaces': 'error',
                'no-restricted-globals': [
                    'error',
                    { message: 'Use `globalThis` instead.', name: 'global' },
                    { message: 'Use `globalThis` instead.', name: 'self' },
                ],
                'no-restricted-properties': [
                    'error',
                    { message: 'Use `Object.getPrototypeOf` or `Object.setPrototypeOf` instead.', property: '__proto__' },
                    { message: 'Use `Object.defineProperty` instead.', property: '__defineGetter__' },
                    { message: 'Use `Object.defineProperty` instead.', property: '__defineSetter__' },
                    { message: 'Use `Object.getOwnPropertyDescriptor` instead.', property: '__lookupGetter__' },
                    { message: 'Use `Object.getOwnPropertyDescriptor` instead.', property: '__lookupSetter__' },
                ],
                'no-restricted-syntax': 'off',
                'no-return-await': 'off',
                'no-self-assign': ['error', { props: true }],
                'no-self-compare': 'error',
                'no-sequences': 'error',
                'no-shadow': 'off',
                'no-shadow-restricted-names': 'error',
                'no-sparse-arrays': 'error',
                'no-template-curly-in-string': 'error',
                'no-this-before-super': 'error',
                'no-throw-literal': 'error',
                'no-undef': 'error',
                'no-undef-init': 'error',
                'no-underscore-dangle': 'off',
                'no-unexpected-multiline': 'error',
                'no-unmodified-loop-condition': 'error',
                'no-unneeded-ternary': ['error', { defaultAssignment: false }],
                'no-unreachable': 'error',
                'no-unreachable-loop': 'error',
                'no-unsafe-finally': 'error',
                'no-unsafe-negation': 'error',
                'no-unused-expressions': ['error', {
                    allowShortCircuit: true,
                    allowTaggedTemplates: true,
                    allowTernary: true,
                }],
                'no-unused-vars': ['error', {
                    args: 'none',
                    caughtErrors: 'none',
                    ignoreRestSiblings: true,
                    vars: 'all',
                }],
                'no-use-before-define': ['error', { classes: false, functions: false, variables: true }],
                'no-useless-backreference': 'error',

                'no-useless-call': 'error',
                'no-useless-catch': 'error',
                'no-useless-computed-key': 'error',
                'no-useless-constructor': 'error',
                'no-useless-rename': 'error',
                'no-useless-return': 'error',
                'no-var': 'error',
                'no-with': 'error',
                'object-curly-newline': 'off',
                'object-shorthand': [
                    'error',
                    'always',
                    {
                        avoidQuotes: true,
                        ignoreConstructors: false,
                    },
                ],
                'one-var': ['error', { initialized: 'never' }],
                'operator-linebreak': ['error', 'before'],
                'prefer-arrow-callback': [
                    'error',
                    {
                        allowNamedFunctions: false,
                        allowUnboundThis: true,
                    },
                ],
                'prefer-const': [
                    isInEditor ? 'warn' : 'error',
                    {
                        destructuring: 'all',
                        ignoreReadBeforeAssign: true,
                    },
                ],
                'prefer-exponentiation-operator': 'error',
                'prefer-promise-reject-errors': 'error',
                'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
                'prefer-rest-params': 'error',
                'prefer-spread': 'error',
                'prefer-template': 'error',
                'semi': ['error', 'never'],
                'space-before-function-paren': ['error', {
                    anonymous: 'never',
                    asyncArrow: 'always',
                    named: 'never',
                }],
                'symbol-description': 'error',
                'template-curly-spacing': 'off',
                'unicode-bom': ['error', 'never'],
                'unused-imports/no-unused-imports': isInEditor ? 'warn' : 'error',
                'unused-imports/no-unused-vars': [
                    'error',
                    {
                        args: 'after-used',
                        argsIgnorePattern: '^_',
                        ignoreRestSiblings: true,
                        vars: 'all',
                        varsIgnorePattern: '^_',
                    },
                ],
                'use-isnan': ['error', { enforceForIndexOf: true, enforceForSwitchCase: true }],
                'valid-typeof': ['error', { requireStringLiterals: true }],
                'vars-on-top': 'error',
                'yoda': ['error', 'never'],

                ...overrides,
            },
        },
    ]
}
